# Generated by Django 5.1.1 on 2024-10-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('birth', models.DateField()),
                ('hobby', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('career', models.CharField(max_length=50)),
            ],
        ),
    ]
